package com.thehellings.demo.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thehellings.demo.db.Comment;
import com.thehellings.demo.db.Post;

/**
 * Class _Comment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Comment extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String BODY_PROPERTY = "body";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String POSTER_PROPERTY = "poster";
    @Deprecated
    public static final String CHILDREN_PROPERTY = "children";
    @Deprecated
    public static final String PARENT_PROPERTY = "parent";
    @Deprecated
    public static final String POST_PROPERTY = "post";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> BODY = new Property<String>("body");
    public static final Property<Integer> ID = new Property<Integer>("id");
    public static final Property<String> POSTER = new Property<String>("poster");
    public static final Property<List<Comment>> CHILDREN = new Property<List<Comment>>("children");
    public static final Property<Comment> PARENT = new Property<Comment>("parent");
    public static final Property<Post> POST = new Property<Post>("post");

    public void setBody(String body) {
        writeProperty("body", body);
    }
    public String getBody() {
        return (String)readProperty("body");
    }

    public void setId(int id) {
        writeProperty("id", id);
    }
    public int getId() {
        Object value = readProperty("id");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPoster(String poster) {
        writeProperty("poster", poster);
    }
    public String getPoster() {
        return (String)readProperty("poster");
    }

    public void addToChildren(Comment obj) {
        addToManyTarget("children", obj, true);
    }
    public void removeFromChildren(Comment obj) {
        removeToManyTarget("children", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Comment> getChildren() {
        return (List<Comment>)readProperty("children");
    }


    public void setParent(Comment parent) {
        setToOneTarget("parent", parent, true);
    }

    public Comment getParent() {
        return (Comment)readProperty("parent");
    }


    public void setPost(Post post) {
        setToOneTarget("post", post, true);
    }

    public Post getPost() {
        return (Post)readProperty("post");
    }


}
