package com.thehellings.demo.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thehellings.demo.db.Comment;
import com.thehellings.demo.db.User;

/**
 * Class _Post was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Post extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String BODY_PROPERTY = "body";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String SUMMARY_PROPERTY = "summary";
    @Deprecated
    public static final String TITLE_PROPERTY = "title";
    @Deprecated
    public static final String COMMENTS_PROPERTY = "comments";
    @Deprecated
    public static final String POSTER_PROPERTY = "poster";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> BODY = new Property<String>("body");
    public static final Property<Integer> ID = new Property<Integer>("id");
    public static final Property<String> SUMMARY = new Property<String>("summary");
    public static final Property<String> TITLE = new Property<String>("title");
    public static final Property<List<Comment>> COMMENTS = new Property<List<Comment>>("comments");
    public static final Property<User> POSTER = new Property<User>("poster");

    public void setBody(String body) {
        writeProperty("body", body);
    }
    public String getBody() {
        return (String)readProperty("body");
    }

    public void setId(int id) {
        writeProperty("id", id);
    }
    public int getId() {
        Object value = readProperty("id");
        return (value != null) ? (Integer) value : 0;
    }

    public void setSummary(String summary) {
        writeProperty("summary", summary);
    }
    public String getSummary() {
        return (String)readProperty("summary");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void addToComments(Comment obj) {
        addToManyTarget("comments", obj, true);
    }
    public void removeFromComments(Comment obj) {
        removeToManyTarget("comments", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Comment> getComments() {
        return (List<Comment>)readProperty("comments");
    }


    public void setPoster(User poster) {
        setToOneTarget("poster", poster, true);
    }

    public User getPoster() {
        return (User)readProperty("poster");
    }


}
