package com.thehellings.demo.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thehellings.demo.db.Post;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String IS_ADMIN_PROPERTY = "isAdmin";
    @Deprecated
    public static final String PASSWORD_PROPERTY = "password";
    @Deprecated
    public static final String USERNAME_PROPERTY = "username";
    @Deprecated
    public static final String POSTS_PROPERTY = "posts";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> IS_ADMIN = new Property<Boolean>("isAdmin");
    public static final Property<String> PASSWORD = new Property<String>("password");
    public static final Property<String> USERNAME = new Property<String>("username");
    public static final Property<List<Post>> POSTS = new Property<List<Post>>("posts");

    public void setIsAdmin(Boolean isAdmin) {
        writeProperty("isAdmin", isAdmin);
    }
    public Boolean getIsAdmin() {
        return (Boolean)readProperty("isAdmin");
    }

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setUsername(String username) {
        writeProperty("username", username);
    }
    public String getUsername() {
        return (String)readProperty("username");
    }

    public void addToPosts(Post obj) {
        addToManyTarget("posts", obj, true);
    }
    public void removeFromPosts(Post obj) {
        removeToManyTarget("posts", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Post> getPosts() {
        return (List<Post>)readProperty("posts");
    }


}
